### PR TITLE
Improved Contact Book

### PR DESCRIPTION
**Pull request by sslp**
+ Add Contacts
+ Show Contact List
+ View Contacts
+ Edit Contacts
+ Delete Contacts

### CODE REVIEW

**Comment by sslp** [comment]
Fixed all bugs I found.

**Comment by sslp** [comment]
Added Autocompletition for Address in SendCoinActiviy

**Comment by holmholk** [comment]
It's working pretty good! Some suggestions:
- In the auto complete suggestions, truncate the middle instead of the end just like what the address book is doing.
- Edit contact screen's title should be "Edit Contact"
- Change strings "Address invalid" to "Invalid address", and "Name missing" to "Missing name". they sound more natural imo

**Comment by sslp** [comment]
```diff
- In the auto complete suggestions, truncate the middle instead of the end just like what the address book is doing.

+ Edit contact screen's title should be "Edit Contact"

+ Change strings "Address invalid" to "Invalid address", and "Name missing" to "Missing name". they sound more natural imo
```
How to truncate the address? Where's the method?

**Comment by sslp** [comment]
Changes applied.

**Pull request merged**
